[allowlist]
  description = "Global Allowlist"

  # Ignore based on any subset of the file path
  paths = [
    # Ignore fast fake user creation
    '''openshift-tweak\/htpasswd''',
    '''minio\/minio.yaml'''
  ]