kind: Secret
apiVersion: v1
metadata:
  name: htpasswd-secret
  namespace: openshift-config
data:
  htpasswd: >-
    YW5kcmV3OiRhcHIxJGRaUGIyRUNmJGVyY2V2T0ZPNXpucnluVWZVajR0Yi8Ka2FybGE6JGFwcjEkRlF4Mm1YNGMkZUpjMjFHdVZaV05nMVVMRjhJMkczMQphZG1pbjokYXByMSRKNllKMVBKayR6TVB3ZUlPeVNGdDA1Umx0YjdZZUMwCnVzZXIxOiRhcHIxJDJESGkyZDhqJGVMZ2V4QTdoRXM3ZDlPUzVvWC91Yi8KdXNlcjI6JGFwcjEkMkRIaTJkOGokZUxnZXhBN2hFczdkOU9TNW9YL3ViLwp1c2VyMzokYXByMSQyREhpMmQ4aiRlTGdleEE3aEVzN2Q5T1M1b1gvdWIvCnVzZXI0OiRhcHIxJDJESGkyZDhqJGVMZ2V4QTdoRXM3ZDlPUzVvWC91Yi8KdXNlcjU6JGFwcjEkMkRIaTJkOGokZUxnZXhBN2hFczdkOU9TNW9YL3ViLwo=
type: Opaque