---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis
  namespace: workshop-guide
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 1Gi
