---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: get-a-username
  name: get-a-username
  namespace: workshop-guide
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: get-a-username
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        deployment: get-a-username
    spec:
      containers:
      - name: get-a-username
        securityContext:
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
        env:
        - name: LAB_ADMIN_PASS
          value: admin
        - name: LAB_DURATION_HOURS
          value: 1week
        - name: LAB_EXTRA_URLS
          value: "https://console-openshift-console.apps.cluster-h4v9k.h4v9k.sandbox932.opentlc.com/;OpenShift Console"
        - name: LAB_MODULE_URLS
          value: "https://intelligent-agriculture-workshop-workshop-guide.apps.cluster-h4v9k.h4v9k.sandbox932.opentlc.com/intelligent-agriculture-workshop/main/1-introduction.html?USERID=%USERNAME%&SUBDOMAIN=apps.cluster-h4v9k.h4v9k.sandbox932.opentlc.com;Intelligent Agriculture Workshop"
        - name: LAB_REDIS_HOST
          value: redis
        - name: LAB_REDIS_PASS
          value: redis
        - name: LAB_TITLE
          value: "Intelligent Agriculture Workshop"
        - name: LAB_USER_ACCESS_TOKEN
          value: openshift
        - name: LAB_USER_COUNT
          value: "50"
        - name: LAB_USER_PAD_ZERO
          value: "false"
        - name: LAB_USER_PASS
          value: openshift
        - name: LAB_USER_PREFIX
          value: user
        image: quay.io/openshiftlabs/username-distribution@sha256:d9e1770fbc92f540d19cdceb830fa18ea0d2c31e2fa52685d3e19543131ed662
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
